name: d3rl-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hydra=2.5=py38h497a2fe_1
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - liblapack=3.9.0=20_linux64_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.5=h2d0b736_3
  - numpy=1.23.5=py38h7042d01_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openssl=3.5.0=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.19=hd12c33a_0_cpython
  - python_abi=3.8=6_cp38
  - pyyaml=6.0.2=py38h2019614_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_0
  - scipy=1.10.1=py38h59b608b_3
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py38h62bed22_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.2.2
      - box2d-py==2.3.5
      - click==8.1.8
      - cloudpickle==3.1.1
      - d3rlpy==2.6.2
      - dataclasses-json==0.6.7
      - etils==1.3.0
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - fsspec==2025.3.0
      - glfw==2.9.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.1.1
      - h5py==3.11.0
      - hydra-core==1.3.2
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - mpmath==1.3.0
      - mujoco==3.2.3
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - pillow==10.4.0
      - pygame==2.6.1
      - pyopengl==3.1.9
      - structlog==25.2.0
      - swig==4.3.0
      - sympy==1.13.3
      - torch==2.4.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - zipp==3.20.2
prefix: /home/mx/miniconda3/envs/d3rl-env
