name: DR-SAC
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - aom=3.6.0=h6a678d5_0
  - blas=2.136=openblas
  - blas-devel=3.9.0=36_h1ea3ea9_openblas
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.0.2=py310hbf28c38_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h1110e0f_2
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.33.3=py310h5764c6d_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h166bdaf_1
  - kiwisolver=1.4.2=py310hbf28c38_1
  - krb5=1.21.3=h8a1dbc1_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=36_h0358290_openblas
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.14.1=h31d0fb7_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblapacke=3.9.0=36_h6ae95b6_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_1
  - libprotobuf=5.29.3=h3cdef7c_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=h7f98852_0
  - libxml2=2.13.8=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.6=py310hff52083_1
  - matplotlib-base=3.10.6=py310h71dd3da_0
  - mesalib=25.1.5=h31e3550_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - nomkl=3.0=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy-base=2.0.1=py310h8a23956_1
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=3.2.4=pyhcf101f3_0
  - pyside6=6.7.3=py310hfe4ef28_1
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - qtbase=6.7.3=h10a5587_2
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtshadertools=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebengine=6.7.3=h5092597_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.2=h5eee18b_0
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py310h5764c6d_3
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.31=h516909a_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - box2d-py==2.3.5
      - cloudpickle==3.1.1
      - etils==1.12.0
      - farama-notifications==0.0.4
      - filelock==3.17.0
      - fsspec==2025.2.0
      - glfw==2.8.0
      - grpcio==1.70.0
      - gymnasium==1.1.0
      - hydra-core==1.3.2
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - markdown==3.7
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - mujoco==3.3.0
      - networkx==3.4.2
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - packaging==24.2
      - pillow==11.1.0
      - pip==25.0.1
      - protobuf==5.29.3
      - pygame==2.6.1
      - pyopengl==3.1.9
      - pyyaml==6.0.2
      - scipy==1.15.2
      - setuptools==75.8.2
      - swig==4.3.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - werkzeug==3.1.3
      - zipp==3.21.0
prefix: /home/mx/miniconda3/envs/DR-SAC
