name: minari-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - attr=2.5.1=h166bdaf_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.10.17=py310hd8ed1ab_0
  - cuda-crt-tools=12.8.93=ha770c72_3
  - cuda-cudart=12.8.90=h5888daf_1
  - cuda-cudart_linux-64=12.8.90=h3f2d84a_1
  - cuda-cuobjdump=12.8.90=hbd13f7d_1
  - cuda-cupti=12.8.90=h5888daf_1
  - cuda-nvcc-tools=12.8.93=he02047a_3
  - cuda-nvdisasm=12.8.90=hbd13f7d_1
  - cuda-nvrtc=12.8.93=h5888daf_1
  - cuda-nvtx=12.8.90=h5888daf_1
  - cuda-nvvm-tools=12.8.93=he02047a_3
  - cuda-version=12.8=h5d125a7_3
  - cudnn=9.8.0.87=h81d5506_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py310he8512ff_3
  - gym=0.26.1=py310hfdc917e_0
  - gym-notices=0.0.8=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libblas=3.9.0=31_hfdb39a5_mkl
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_h372d94f_mkl
  - libcublas=12.8.4.1=h9ab20c4_1
  - libcudss=0.5.0.16=h14340ca_1
  - libcufft=11.3.3.83=h5888daf_1
  - libcufile=1.13.1.3=h628e99a_1
  - libcurand=10.3.9.90=h9ab20c4_1
  - libcusolver=11.7.3.90=h9ab20c4_1
  - libcusparse=12.5.8.93=h5888daf_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgpg-error=1.51=hbd13f7d_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=31_hc41d3b0_mkl
  - libllvm20=20.1.2=ha7bfdaf_0
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libmagma=2.9.0=h19665d7_1
  - libmpdec=4.0.0=h4bc722e_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.8.93=h5888daf_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libprotobuf=5.29.3=h501fc15_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libtorch=2.6.0=cuda126_mkl_h99b69db_304
  - libudev1=257.4=hbe16f8c_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libxml2=2.13.7=h81593ed_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.2=h024ca30_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py310h89163eb_1
  - mkl=2024.2.2=ha957f24_16
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nccl=2.26.2.1=ha44e49d_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - numpy=1.26.4=py310hb13e2d6_0
  - openssl=3.5.0=h7b32b05_0
  - optree=0.15.0=py310h3788b33_0
  - pip=25.0.1=pyh8b19718_0
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - python=3.10.0=h543edf9_3_cpython
  - python_abi=3.10=6_cp310
  - pytorch=2.6.0=cuda126_mkl_py310_h5ee0071_304
  - rdma-core=56.1=h5888daf_1
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - sleef=3.8=h1b44611_0
  - sqlite=3.49.1=h9eae976_2
  - sympy=1.13.3=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.67.1=pyhd8ed1ab_1
  - triton=3.2.0=cuda126py310h50ec074_1
  - typing-extensions=4.13.1=hf5ce1d7_0
  - typing_extensions=4.13.1=pyh29332c3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - alembic==1.15.2
      - certifi==2025.1.31
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataproperty==1.1.0
      - farama-notifications==0.0.4
      - fonttools==4.57.0
      - greenlet==3.2.0
      - gymnasium==1.1.1
      - h5py==3.13.0
      - huggingface-hub==0.30.2
      - huggingface-sb3==3.0
      - idna==3.10
      - kiwisolver==1.4.8
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - minari==0.5.3
      - optuna==4.3.0
      - packaging==24.2
      - pandas==2.2.3
      - pathvalidate==3.2.3
      - pillow==11.2.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==14.0.0
      - rl-zoo3==2.6.0
      - sb3-contrib==2.6.0
      - shellingham==1.5.4
      - shimmy==2.0.0
      - six==1.17.0
      - sqlalchemy==2.0.40
      - stable-baselines3==2.6.0
      - tabledata==1.3.4
      - tcolorpy==0.1.7
      - typepy==1.3.4
      - typer==0.15.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wasabi==1.1.3
prefix: /home/mx/miniconda3/envs/minari-env
