# @package _global_

# LunarLanderContinuous environment config

env_name: LunarLanderContinuous-v3
env_index: 2
reward_adapt: true
eval_freq: 1000
save_interval: 1000
max_trn_steps: 10000
max_vae_trn_step: 1000
