# @package _global_

env_name: Reacher-v5
env_index: 6
eval_freq: 100
eval_interval: 100
save_interval: 100
max_trn_steps: 10000
max_vae_trn_step: 3000


# # Adam stepsize*
# adam_lr: 1e-3
# # learning rate of actor
# actor_lr: 8e-4
# critic_lr: 8e-4