# @package _global_

# Ant environment config

env_name: Ant-v5
env_index: 5
max_train_steps: 1000000 # 1000k for non-robust, 600k for robust
eval_interval: 5000
reward_adapt: true
n_critic: 10 # Changed from 20 to 2 for standard SAC
net_layer: 4

# Training hyperparameters
a_lr: 0.00003 # 3e-4
c_lr: 0.00001 # 1e-4
g_lr: 0.00005 # 5e-5
r_lr: 0.00005 # 5e-4
# bc_pretrain_steps: 50000
# bc_pretrain_log_interval: 5000
# rollout_after_bc: true
# rollout_steps: 200000
# rollout_epsilon: 0.05

# Generative model parameters
gen_steps: 100000 # 100k
vae_latent_dim: 64

adaptive_alpha: true # Changed from false to true
initial_alpha: 0.1
