# @package _global_

# LunarLanderContinuous environment config

env_name: LunarLanderContinuous-v3
env_index: 2
reward_adapt: true
max_train_steps: 50000 # 50k
n_critic: 2

# Training hyperparameters
a_lr: 0.0005 # 5e-4
c_lr: 0.0005 # 5e-4
g_lr: 0.0005 # 5e-5
r_lr: 0.0005 # 5e-4

# Generative model parameters
gen_steps: 10000 # 10k
vae_latent_dim: 10