# @package _global_

# LunarLanderContinuous environment config
# Benchmark Reward: 250, std: 25
env_name: LunarLanderContinuous-v3
env_index: 2
reward_adapt: true
max_train_steps: 50000 # 50k
vae_steps: 10000
latent_dim: 10
n_critic: 5
a_lr: 0.0005 # 5e-4
c_lr: 0.0005 # 5e-4
b_lr: 0.0005 # 5e-5
g_lr: 0.0005 # 5e-4
r_lr: 0.0005 # 5e-4