# @package _global_

# Pendulum environment config

env_name: Pendulum-v1
env_index: 0
reward_adapt: true
max_train_steps: 10000 # 10k for non-robust, 15k for robust
gen_steps: 5000

# Training hyperparameters
a_lr: 0.0005 # 5e-4
c_lr: 0.0005 # 5e-4
b_lr: 0.00005 # 5e-5
r_lr: 0.00005 # 5e-5

# Diffusion parameters
timesteps: 50
time_embed_dim: 32
beta_start: 0.0001 # 1e-4
beta_end: 0.01 # 1e-2