# @package _global_

env_name: Reacher-v5
env_index: 4
max_train_steps: 50000 # 50k
gen_steps: 5000 # 5k
n_critic: 5
latent_dim: 10
a_lr: 0.0003 # 3e-4
c_lr: 0.0003 # 3e-4
g_lr: 0.00005 # 5e-5
r_lr: 0.0005 # 5e-4

